# Numpy


- A powerful N-dimensional array object
- Broadcasting functions
- Useful linear algebra
- Tools for intergrating C/c++

## 1. Array

Array is the main object of Numpy

Defined by calling numpy.array, comma-separated with squared brackets and parathesis outside

same charateristics as list

- used for stored data
- both are mutable
- can be indexed and iterated
- can be sliced
- ordered


Difference with list

- can only stored same type object in array
- array can perform operation which is more efficient



In [26]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
## Number of Array dimension (which is called RANK)
arr.ndim

2

In [4]:
## Get the shape of array
arr.shape

(2, 3)

In [5]:
## Reshape
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
## Slice
arr[1:,1:]

array([[5, 6]])

In [8]:
## Add element: Note Numpy don't have append function
arr.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [27]:
arr=np.append(arr,[3,6,7]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 7]])

## 2. Broadcast functions

Broadcasting allows operations to be performed on arrays of different sizes.


It happens when add a array which has n*1 dimension or 1*n dimnesion, or just 1 scala element

** Rules: **

- If the two arrays differ in dimensions, the shape of one with fewer dimensions is padded with ones on its leading
- if the shape of two arrays does not match in any dimension, the dimension of the array with the shape equal to 1 will stretched to match to other shape
- otherwise, error rasied


In [31]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [37]:
## Element-wise add method
a+np.array([1,1,1])

array([2, 3, 4])

In [34]:
## perform broadcasting on a by add 1 on every element
a+1

array([2, 3, 4])

In [35]:
c=np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
## Broadcasting a on c
c+a

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

## 3. Linear Algebra

** numpy.linalg **

Refer to: 
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html


This package can get the eigenvalues of matrix or array, inverse a matrix, solve linear euqation


### 3.1 simple equation

In [5]:
## Solving:
## 1a+1b=35
## 2a+9b=60
a=np.array([[1,1],[2,9]])
b=np.array([35,60])
np.linalg.solve(a,b)

array([36.42857143, -1.42857143])

### 3.2 Math

- basic function, such as np.exp(), np.sum()

In [3]:
np.exp(3)

20.085536923187668

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
## keepdims set the result to make sure the result is what we want
## For example, make sure the result is (4,1), not (4,)
np.sum(a, axis=1, keepdims=True)

array([[ 6],
       [15],
       [24]])

### 3.3 Using Vectorization to decrease running time

In [10]:
x1 = [9, 2, 5, 0]
x2 = [9, 2, 2, 9]

In [11]:
## np.dot: mutiply data directly:
## 9*9 +2*2+2*5+0*9
np.dot(x1,x2)

95

In [14]:
## np.outer: mutiply every single element
##  result[0,0]=9*9, result[0,1]=9*2,result[0,2]=9*2.....
np.outer(x1,x2)

array([[81, 18, 18, 81],
       [18,  4,  4, 18],
       [45, 10, 10, 45],
       [ 0,  0,  0,  0]])

In [15]:
## elementwise implementation
## result[0,1]=9*9, result[0,2]=2*2 ....
np.multiply(x1,x2)

array([81,  4, 10,  0])