# Python Data structure

## 1- List

List is like a array but more flexible, which is define in a enclosing a comma-separated sequence of objects in a squre brackets

*** List characteristics ***
- List are ordered
- Can be accessed by index
- are mutable
- are dynamic
- Can contain value in different type

In [23]:
a=['a','b','c']
a[2]=1
a

['a', 'b', 1]

### List methods

In [24]:
# Add value: list.append(x)
a.append('d')
a

['a', 'b', 1, 'd']

In [28]:
# insert: list.insert(index to insert, value)
a.insert(1,'hi')
a

['a', 'hi', 'b', 1, 'd']

In [29]:
# Remove
a.remove('hi')
a

['a', 'b', 1, 'd']

In [30]:
# remove the item at given postion and return it. If no index given, it remove last element
a.pop(3)

'd'

In [31]:
a

['a', 'b', 1]

In [32]:
a.pop()
a

['a', 'b']

In [ ]:
# Clear list: list.clear() = del list[:]
# a.clear() = del a[:]

In [34]:
# Sort: list.sort( key= None, reverse =False)
a.sort()
a

['a', 'b']

In [37]:
# Count how many times of x appears in list: list.count(X)
a.count('a')

1

## 2-Tuple

Tuple is defined by a comma-separated sequence of objects in a ***parentheses*** instead of squared brackets

- can be accessed by index
- tuple are ***immutable***, thus there is no append() or pop() function for tuple
- tuple are ordered
- Can contain duplicates value

*** Benifit of a tuple than List ***

- Program run faster for a tuple than list since tuple have a smaller size than list
- Avoid data to be modified



In [66]:
a=(1,2,3)
a[2]=1

TypeError: 'tuple' object does not support item assignment

In [67]:
# Get slice of tuple
a[1:3]

(2, 3)

In [39]:
# Why tuple is efficient than list
a=(3,)
b=[3]
print('size of a:{} \nsize of b:{}'.format(a.__sizeof__(),b.__sizeof__()))

size of a:32 
size of b:48


In [20]:
## create null tuple
t=()
type(t)

tuple

*** Note when you want to define a only one object tuple ***

In [21]:
t=(3)
type(t)

int

In [22]:
t=(3,)
type(t)

tuple

### Tuple method

In [74]:
# Tuple concate
a=(1,2,3)
b=(5,6,7)
c=a+b
c

(1, 2, 3, 5, 6, 7)

In [70]:
# Add item: since tuple is not changable after defined, append value will cause error
c[7]=7
c

TypeError: 'tuple' object does not support item assignment

In [81]:
# Tuple add value by using concate, and tuple are not unique
c=c+(8,9,8,9,)
c

(1, 2, 3, 5, 6, 7, 8, 9, 8, 9)

In [83]:
# insert value at index 3
c=c[:3]+(6,)+c[3:]
c

(1, 2, 3, 6, 3, 5, 6, 7, 8, 9, 8, 9)

In [84]:
# remove item from tuple
c=c[:10]
c

(1, 2, 3, 6, 3, 5, 6, 7, 8, 9)

In [73]:
# drop tuple
del c

NameError: name 'c' is not defined

## 3-Array

Defined by calling numpy.array, comma-separated with squared brackets and parathesis outside

same charateristics as list

- used for stored data
- both are mutable
- can be indexed and iterated
- can be sliced
- ordered


Difference with list

- can only stored same type object in array
- array can perform operation which is more efficient


In [8]:
import numpy as np
a=np.array([1,2,3])
a/2

array([0.5, 1. , 1.5])

In [9]:
a[-1]

3

In [10]:
b=[1,2,3]
b/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [11]:
# Add value
a[0]=0
a

array([0, 2, 3])

In [15]:
# while numpy.array don't have the append function
a.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [19]:
# use numpy.append instead
import numpy as np
np.append(a,2)

array([0, 2, 3, 2])

In [20]:
# not unique
a=np.array([2,3,4,2])
a

array([2, 3, 4, 2])

## 4-Dictionary


Dictionary defined by commas-separed pairs value in a curly braces.

- Keys are immutable (not able to change)
- Value are mutable
- Key should be distinct
- Keys are not orderd

In [2]:
d={'a':1,'b':2,'c':3}

In [3]:
d[1]

KeyError: 1

In [4]:
# Not work since dictionary is not ordered
d['a']

1

In [5]:
sorted(d.keys())

['a', 'b', 'c']

In [6]:
# Get dictionary data
d['a']

1

In [7]:
# Add value
d['d']=4
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

## 5- Sequence


Sequence include tuple, string, set


## 6 -Set

Set are defined by two ways:
> 1. defined as comma-separated value in squred brackets and parethesis
> 2. defined as curly brackest

- Set are unordered different with array
- Set are unique not dupliate
- Set are not subscritable which can only access through for loop, can't use list['a']


In [47]:
# Set are not duplicates
b=set(['a','b','ais','bdfdf','ais','a'])
b

{'a', 'ais', 'b', 'bdfdf'}

In [ ]:
type(b)

In [59]:
a={'a','b','ais','bdfdf','ais','a'}

In [ ]:
type(a)

In [40]:
## Unordered
b[1]

TypeError: 'set' object does not support indexing

In [41]:
# not subscriptable
b['a']

TypeError: 'set' object is not subscriptable

In [48]:
for x in b:
    print(x)

a
bdfdf
ais
b


### Set methods

In [60]:
# Add items:
b.add('oranges')
b

{'ais', 'bdfdf', 'oranges'}

In [61]:
# Update: Add multiple data in sets while it only has unique value
b.update(['a', 'ais', 'b', 'bdfdf', 'apple', 'banana'])
b

{'a', 'ais', 'apple', 'b', 'banana', 'bdfdf', 'oranges'}

In [62]:
# remove item
b.remove('apple')
b

{'a', 'ais', 'b', 'banana', 'bdfdf', 'oranges'}

In [63]:
# Pop value
b.pop()
b

{'a', 'ais', 'b', 'banana', 'bdfdf'}

In [64]:
# len of set
len(b)

5

## Summary

<img src="Data_structure.png" alt="Alt text that describes the graphic" title="Title text" />

### Type transfered

In [29]:
a=(1,3,4)
type(a)

tuple

In [32]:
# Change tuple to array
b=np.asarray(a)
type(b)

numpy.ndarray

In [33]:
b

array([1, 3, 4])

In [34]:
# change Tuple to list
c=list(a)
type(c)

list

In [35]:
c

[1, 3, 4]

In [36]:
# list to tuple
d=tuple(c)
type(d)

tuple